{% set name = "aniso8601" %}
{% set version = "7.0.0" %}
{% set sha256 = "513d2b6637b7853806ae79ffaca6f3e8754bdd547048f5ccc1420aec4b714f1e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - python-dateutil

test:
  imports:
    - aniso8601

about:
  home: https://bitbucket.org/nielsenb/aniso8601
  license: BSD 3-Clause
  summary: A library for parsing ISO 8601 strings.

extra:
  recipe-maintainers:
    - vamega
