{% set name = "aniso8601" %}
{% set version = "10.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25488f8663dd1528ae1f54f94ac1ea51ae25b4d531539b8bc707fed184d16845

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - aniso8601
    - aniso8601.builders
    - aniso8601.builders.python
    - aniso8601.compat
    - aniso8601.date
    - aniso8601.decimalfraction
    - aniso8601.duration
    - aniso8601.exceptions
    - aniso8601.interval
    - aniso8601.resolution
    - aniso8601.tests.compat
    - aniso8601.time
    - aniso8601.timezone
    - aniso8601.utcoffset
  commands:
    - pip check
    - pytest --pyargs aniso8601.tests
  requires:
    - pip
    - pytest
    - mock >=2.0.0

about:
  home: https://codeberg.org/nielsenb-jf/aniso8601
  summary: A library for parsing ISO 8601 strings.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: Another ISO 8601 parser for Python
  dev_url: https://codeberg.org/nielsenb-jf/aniso8601
  doc_url: https://aniso8601.readthedocs.io
  

extra:
  recipe-maintainers:
    - vamega
