{% set name = "aniso8601" %}
{% set version = "3.0.0" %}
{% set sha256 = "7cf068e7aec00edeb21879c2bbda048656c34d281e133a77425be03b352122d8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-dateutil

test:
  imports:
    - aniso8601

about:
  home: https://bitbucket.org/nielsenb/aniso8601
  license: BSD 3-Clause
  summary: A library for parsing ISO 8601 strings.

extra:
  recipe-maintainers:
    - vamega
