travis:
  secure:
    BINSTAR_TOKEN: HEjuXXxHuUUBmo9xz8Gb0MPkmliJ67oQGfBBIcSU1Op740YFEfOPIU85cBbL6ZlxHmLlYLbXXAv37JsGSfGerRP7zt8uLwo/9GX0PZH1awBX+vDsNkJlr648CVpN//U8/64ZTHyDua59C5lFjry0Ononc5RloVvpkAGYE+7cwQ6K4fYtEl54kYKTQrrML4b4iDHR9QqA9ylkaWv6jR4z0Tiary4Z7ucO0ksMEke3nuJdUFnU7tfWvAoIdZ+TrlnufnzQcIlOWSngisqJZx0HCwNxrpoCy42As0lO2OrNIbuIg75Z44gtdKeqU0eG12Gp9AlvGoCFCJhccTZGhSG/0L6gh7rayOw6n9MtXq94j1i06Ssnf4V15cWtwVR78FTUlKrViWvpP+q6Dl0SNj6RXtQUMCXIzPqD4cRTfHZI9NWvedsMKbZlXvAVypZi/B3AzXKJv4q5/PNewHRZlUq98eUToAIL3JD63Q2chvBO0iEOIzJJHYsR7qVY6uEJj5EajagDLKNGhxLhnQXrfdrf92fh4CNpSF25S0zPV/qoTQgJyTtzNZvZ7xbW5Wq8cxqZo8uzDQ1NwDPqK0YLaVQtFAs2grzMhho8CSRY0ixH8lfxtsyhZ7BOuyrSSwOhXHd5xCQRERazRoMNb6UHz4j4szMISqKmPmBJcEobstWTOG8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
