travis:
  secure:
    BINSTAR_TOKEN: k6ISjl85bjRjCX8FhSbuTN4SyZRz/r/l2IBD9IbJFUSLt71I2AAM9e0rcj7rX7dkSCfai0xOQO9Fscw9Ugpfx6HGfwjv6iPXZzSgahh6OsQJ7nyJNRxgblM5KjnjsEOZ5drKiWNSNZ+a3A2hhld0Gg4gWfHdTIidE+21B5eiJ0RnCkU/dyG3G/a8CcqvblNvVS9pUzJyosIzi1s7g+47hqp872pIOqY9mbDbZyxHNZ3AQ2g+idRPRZmsJlxqYVAm+48PSWt3GYlhQTl2b1LKud3Uj/wOYP5lPZdVbzC53mpv1NlIQ2azt/HNbOgZHo5+OrmEjj/nv6qvkKfeNQxZ/HvfiVS/Iy3rfEEeqhwlFOpskajf3hOP4eyWElXT0fTUpj/KOFhe3Sg/OufV1A4SxT2RDzoGh3w3vMRbN5+lJyHdptthpK+gGcsP6bxPwjZcQR8totn52XXNX4bIXgLiISvnZc+whhxfqaMAyqSWZUzSgcMEDTF9pIJjxf0ITlYH4FWLaXt+3obiej0TsUoO8ZZMySS7OGEjMnUlPQrBxPV7lEzy1n+jy405tK2/V+l1KC4CSRDAFj38O538MmUWDpaNr3zfJ3038QUngvoTaoKXnbsTH3KcZ2AxB0yEMeBMP7zBUZysu4oXsrKnrhbfySTsFB9hoyw9ZEOB0nOarCE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
