travis:
  secure:
    BINSTAR_TOKEN: KAeZJZXH+gM/giBeyzhAXTaGxlHEzd+pckyymM8o+U+XREVNxf9hZQStVdWoftN9NZBvbEwl8NT6dSNk5fINE6z0zKZkeC7DIXL9uVFcj/sUMkzWAfxm5gkErlOQY+vsKAOAcu+dbpvp07vUSfbggvw3FsbUeLsoZroYJ2Hh8SAFOaEdLKZjDsw9hgHQEyzfda/HUq0j4Yora1Ka5hVtuzn/WEn6BYRZM94aTtstsIK4+LvThR17Yl5U7HCJ7cXo42QrtRjUj0g9Dfnh38DatoMDhdilrRz5+qIub8W5x0X8Lf4yZ+ngNgTZuxrp9Vp3AUEMiNlAqD14+wltK3q3rGUkOzhA0pMT6/O0QNlmA3KlwSnf80uOygke/dM5Gyl2odMV1srwPUJkHAsrVAjOozvCUK+FvlqKK3XJkBhk0FKa3eWx9uGSIypWMPF1+zBZY8Yt2RGifrRHGLlIyCmCB72WAnef4apUFC/Xmbs/gUKeK9nhvJbJxnpFBOyOYLZhgDOzI97MD/BpvKUlo36Qcjp3VP74S8EI7hA+0woOqThYH7/nWXHAYttsDADyh4cipzz68DSyKlyAw+9WvthjlOKPK4NdzMu3CZpq5aegoN1Ucu8NdaADfzVopbbJcxKImyoce6RaPXLhbriXte+2oN4khRc8UlRaI0ASuWGfvx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
